### ISSUE TITLE
can we have trained model weight?

### ISSUE THREAD

**Issue by penolove** [X-LANCE/TIE#1]
my gpu is 3060 with 12G ram and can only train with batch_size = 2, each epoch requires 52 hours to train, are we able to have some trained wight to test the result? thank you!

**Comment by TravelLeraLone** [comment]
Sorry for the late reply!

You can download the weight of TIE trained on WebSRC dataset by this link: "https://x-lance.s3.us-west-1.amazonaws.com/TIE_WebSRC.bin" (It is saved by the save_pretrained api provided by hugginface). Hope it will help your research.

**Comment by runningabcd** [comment]
> https://x-lance.s3.us-west-1.amazonaws.com/TIE_WebSRC.bin

链接已经拒绝访问，麻烦重新发下链接吧，是否考虑上传到 huggingface 呢

**Comment by runningabcd** [comment]
> Sorry for the late reply!
> 
> You can download the weight of TIE trained on WebSRC dataset by this link: "https://x-lance.s3.us-west-1.amazonaws.com/TIE_WebSRC.bin" (It is saved by the save_pretrained api provided by hugginface). Hope it will help your research.

还有个问题想咨询下，TIE和 MarkupLM 相比，其实就增加了个节点间的拓扑关系，这些 markuplm 中的 xpath embedding 层理论上可以学习到的，毕竟 xpath 的路径是从根节点到子节点

**Comment by runningabcd** [comment]
> > Sorry for the late reply!
> > You can download the weight of TIE trained on WebSRC dataset by this link: "https://x-lance.s3.us-west-1.amazonaws.com/TIE_WebSRC.bin" (It is saved by the save_pretrained api provided by hugginface). Hope it will help your research.
> 
> 还有个问题想咨询下，TIE和 MarkupLM 相比，其实就增加了个节点间的拓扑关系，这些 markuplm 中的 xpath embedding 层理论上可以学习到的，毕竟 xpath 的路径是从根节点到子节点

问这个问题的目的是，空间拓扑关系必须用 GAT 才能学习到吗？感谢

**Comment by runningabcd** [comment]
@TravelLeraLone 同学，辛苦回答下，麻烦啦

**Comment by TravelLeraLone** [comment]
> > https://x-lance.s3.us-west-1.amazonaws.com/TIE_WebSRC.bin
> 
> 链接已经拒绝访问，麻烦重新发下链接吧，是否考虑上传到 huggingface 呢

Sorry. We have shared the weight of TIE trained on WebSRC dataset through google drive. You can download it by [this link](https://drive.google.com/file/d/1HRaPjDKARL7Xx33VmKHojOZeeZ2YwW1v/view?usp=drive_link).

**Comment by TravelLeraLone** [comment]
> > Sorry for the late reply!
> > You can download the weight of TIE trained on WebSRC dataset by this link: "https://x-lance.s3.us-west-1.amazonaws.com/TIE_WebSRC.bin" (It is saved by the save_pretrained api provided by hugginface). Hope it will help your research.
> 
> 还有个问题想咨询下，TIE和 MarkupLM 相比，其实就增加了个节点间的拓扑关系，这些 markuplm 中的 xpath embedding 层理论上可以学习到的，毕竟 xpath 的路径是从根节点到子节点

markuplm中的xpath实际上就是通过隐式的方式将逻辑关系引入模型，这当然是可行的。实际上直接使用HTML的H-PLM（WebSRC: A Dataset for Web-Based Structural Reading Comprehension）也可以认为是将逻辑关系隐式的通过HTML代码引入模型。其中主要的区别就在于建模难度，引入的方式越抽象模型学习和建模的难度就越大，因此这三个方法会在最终性能上表现出差异。此外，还有一个区别是，空间关系是不存在于xpath和纯HTML中的。

**Comment by runningabcd** [comment]
> > > Sorry for the late reply!
> > > You can download the weight of TIE trained on WebSRC dataset by this link: "https://x-lance.s3.us-west-1.amazonaws.com/TIE_WebSRC.bin" (It is saved by the save_pretrained api provided by hugginface). Hope it will help your research.
> > 
> > 
> > 还有个问题想咨询下，TIE和 MarkupLM 相比，其实就增加了个节点间的拓扑关系，这些 markuplm 中的 xpath embedding 层理论上可以学习到的，毕竟 xpath 的路径是从根节点到子节点
> 
> markuplm中的xpath实际上就是通过隐式的方式将逻辑关系引入模型，这当然是可行的。实际上直接使用HTML的H-PLM（WebSRC: A Dataset for Web-Based Structural Reading Comprehension）也可以认为是将逻辑关系隐式的通过HTML代码引入模型。其中主要的区别就在于建模难度，引入的方式越抽象模型学习和建模的难度就越大，因此这三个方法会在最终性能上表现出差异。此外，还有一个区别是，空间关系是不存在于xpath和纯HTML中的。

非常感谢
