### ISSUE TITLE
训练数据构造

### ISSUE THREAD

**Issue by runningabcd** [X-LANCE/TIE#2]
我这边目前只有 html 文件，如何自动构造对应的 json 文件？有快速构建方式吗？麻烦指导下

**Comment by TravelLeraLone** [comment]
您好，构造json文件的方法请参考[Data Preparing](https://github.com/X-LANCE/TIE?tab=readme-ov-file#data-preparing)一节。

**Comment by runningabcd** [comment]
> 您好，构造json文件的方法请参考[Data Preparing](https://github.com/X-LANCE/TIE?tab=readme-ov-file#data-preparing)一节。

看了 websrc 数据的论文，已了解数据构造过程和整体结构，感谢
